version: "3.7"

# To execute docker-compose in real-time: docker-compose up
# To execute docker-compose in background: docker-compose up -d
# To see logs: docker logs rentx -f

services:
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
