version: "3.7"

# To execute docker-compose in real-time: docker-compose up
# To execute docker-compose in background: docker-compose up -d
# To see logs: docker logs rentx -f

# To execute and recreate: docker-compose up --force-recreate

services:
  database:
    image: postgres
    container_name: postgres_rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local
